### ISSUE TITLE
Howto use libcoap

### ISSUE THREAD

**Issue by smlng** [smartuni/Environ.me#1]
Hi all,

for those of you running into trouble compiling and using _libcoap_ on linux, we created a short guide in the examples wiki, see here https://github.com/smartuni/examples/wiki/libcoap

Cheers

**Comment by MonsterCode8000** [comment]
Thanks for your help.
But it does not really work in my case.
I did the following:
`sudo apt-get install autoconf automake libtool`
`git clone https://github.com/obgm/libcoap.git`
`cd libcoap`
`./autogen.sh --no-documentation`

so fare all is fine I think.
but `make` only returns an error:

> pi@raspberrypi ~/libcoap $ ./autogen.sh --no-documentation
> [HINT] You can run 'autogen.sh --clean' to remove all generated files by the autotools.
> Found 'autoconf'.
> Found 'aclocal'.
> Couldn't find 'libtool'!
> Found 'libtoolize'.
>  --->  Found all needed tools! That's fine.
> Generating needed autotools files for libcoap by running autoreconf ...
> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force ${ACLOCAL_FLAGS} -I m4
> autoreconf: configure.ac: tracing
> autoreconf: running: libtoolize --copy --force
> libtoolize: putting auxiliary files in`.'.
> libtoolize: copying file `./ltmain.sh'
> libtoolize: putting macros in AC_CONFIG_MACRO_DIR,`m4'.
> libtoolize: copying file `m4/libtool.m4'
> libtoolize: copying file`m4/ltoptions.m4'
> libtoolize: copying file `m4/ltsugar.m4'
> libtoolize: copying file`m4/ltversion.m4'
> libtoolize: copying file `m4/lt~obsolete.m4'
> autoreconf: running: /usr/bin/autoconf --force
> autoreconf: running: /usr/bin/autoheader --force
> autoreconf: running: automake --add-missing --copy --force-missing
> configure.ac:29: installing './ar-lib'
> configure.ac:25: installing './compile'
> configure.ac:33: installing './config.guess'
> configure.ac:33: installing './config.sub'
> configure.ac:18: installing './install-sh'
> configure.ac:18: installing './missing'
> Makefile.am: installing './INSTALL'
> Makefile.am: installing './depcomp'
> autoreconf: Leaving directory`.'
> You can now run 'configure --help' to see possible configuration options.
> Otherwise process the configure script to create the makefiles and generated helper files.
> pi@raspberrypi ~/libcoap $ make
> make: **\* Keine Targets angegeben und keine »make«-Steuerdatei gefunden.  Schluss.
> pi@raspberrypi ~/libcoap $

**Comment by smlng** [comment]
Hi again,

you forgot to run the configure script! 

Re-run everything as follows:

```
    git clone https://github.com/obgm/libcoap.git
    cd libcoap
    ./autogen.sh
    ./configure --no-documentation
    make
    sudo make install
```

This should work, afterwards you can use the library.

**Comment by MonsterCode8000** [comment]
Hello,

sorry but it is still not working.

At fist one question is this right:
`gcc -I /usr/local/include/coap client.c coap_list.c -o client.o -lcoap-1 -DWITH_POSIX`
I used
`gcc -I /usr/local/include/coap client.c coap_list.c -o client -lcoap-1 -DWITH_POSIX`

I did this

```
sudo apt-get install autoconf automake libtool
git clone https://github.com/obgm/libcoap.git
cd libcoap
./autogen.sh
./configure --disable-documentation #--no-documentation did not work in my case
make
sudo make install
```

then
case 1

```
pi@raspberrypi ~/libcoap/examples $ gcc -Wall -Wextra  -I /usr/local/include/coap client.c coap_list.c -o client -lcoap-1 -DWITH_POSIX
client.c:11:25: fatal error: coap_config.h: Datei oder Verzeichnis nicht gefunden
compilation terminated.
```

I have not moved the examples folder but this should not make a different.

case 1b

the same as case 1 but I also copied the coap_config.h file into the examples folder.

Than I did

```
pi@raspberrypi ~/libcoap/examples $ gcc -Wall -Wextra  -I /usr/local/include/coap client.c coap_list.c -o client -lcoap-1 -DWITH_POSIX`
pi@raspberrypi ~/libcoap/examples $ ./client 
./client: error while loading shared libraries: libcoap-1.so.0: cannot open shared object file: No such file or directory
```

I looked for the library-path and it exist:

```
pi@raspberrypi / $ cd /usr/local/include/coap/`
pi@raspberrypi /usr/local/include/coap $ ls
address.h  bits.h   coap.h     coap_time.h  encode.h   mem.h  option.h  prng.h      str.h        t_list.h  uthash.h
async.h    block.h  coap_io.h  debug.h      hashkey.h  net.h  pdu.h     resource.h  subscribe.h  uri.h     utlist.h
```

Some one am Idea what I am doing wrong?

**Comment by josephnoir** [comment]
Can you locate the lib? It should be called `libcoap-1.so.0` and in on of the folders `/usr/local/lib/` or `/usr/lib`. If not, try `find / -name "libcoap*.so*" 2>/dev/null`.

**Comment by MonsterCode8000** [comment]
```
pi@raspberrypi /usr/local/lib $ ls
libcoap-1.a  libcoap-1.la  libcoap-1.so  libcoap-1.so.0  libcoap-1.so.0.0.0  pkgconfig  python2.7  python3.2  python3.4  site_ruby
```

It seems to be there

**Comment by josephnoir** [comment]
Might not be a default location, try adding `-L/usr/local/lib` to the gcc arguments.

**Comment by MonsterCode8000** [comment]
If I made all right it is still not working. See my Terminal output:

```
pi@raspberrypi ~/libcoap/examples $ gcc -Wall -Wextra -I /usr/local/include/coap -L/usr/local/lib client.c coap_list.c -o client -lcoap-1 -DWITH_POSIX
pi@raspberrypi ~/libcoap/examples $ ./client 
./client: error while loading shared libraries: libcoap-1.so.0: cannot open shared object file: No such file or directory
```

**Comment by josephnoir** [comment]
Yes. My absence from using Linux for development is showing. Guess you need to set the `LD_LIBRARY_PATH`.

```
export LD_LIBRARY_PATH=/usr/local/lib
```

**Comment by MonsterCode8000** [comment]
how to do this?
enter `export LD_LIBRARY_PATH=/usr/local/lib` into the terminal or what should I do?

**Comment by MonsterCode8000** [comment]
it works into the terminal

**Comment by MonsterCode8000** [comment]
and I can compile the coap-cliend myself.
Thanks!

**Comment by josephnoir** [comment]
Yes, reread your previous comment and saw that the compilation worked there. Looks like the `-L...` wasn't the issue, sorry.

**Comment by MonsterCode8000** [comment]
so it should work without `-L...`?

**Comment by josephnoir** [comment]
Looks like it. If you are curious, try it. Btw, the executable name should not end with `.o` and I corrected the command in the wiki.

**Comment by MonsterCode8000** [comment]
after restart I have to to do `export LD_LIBRARY_PATH=/usr/local/lib` again.

**Comment by smlng** [comment]
Right! 

The `export` is only valid for the current terminal/shell - which means after restart or if you open another terminal you have to do the export again. 

To make the `export` permanent, add the following line to your `$HOME/.bashrc`:

```
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
```

**Comment by MonsterCode8000** [comment]
I will try this later.

now I added the mysql stuff into the example client.
Then the compiler failed:

```
$ gcc -Wall -Wextra -I /usr/local/include/coap -L/usr/local/lib client.c coap_list.c -o client $(mysql_config --cflags --libs) -lcoap-1 -DWITH_POSIX`
[...]
In file included from /usr/local/include/coap/coap.h:50:0,
                 from client.c:28:
/usr/local/include/coap/t_list.h:105:1: error: conflicting types for ‘list_add’
/usr/include/mysql/my_list.h:30:14: note: previous declaration of ‘list_add’ was here
/usr/local/include/coap/t_list.h:111:1: error: expected ‘)’ before ‘the_list’
/usr/local/include/coap/t_list.h:116:1: error: expected identifier or ‘(’ before ‘{’ token
/usr/local/include/coap/t_list.h:116:27: error: expected identifier or ‘(’ before ‘{’ token
/usr/local/include/coap/t_list.h: In function ‘list_insert’:
/usr/local/include/coap/t_list.h:128:5: warning: passing argument 2 of ‘list_cons’ from incompatible pointer type [enabled by default]
/usr/include/mysql/my_list.h:32:14: note: expected ‘struct LIST *’ but argument is of type ‘list_t’
/usr/local/include/coap/t_list.h:128:5: warning: assignment from incompatible pointer type [enabled by default]'
```

A test program with only Mysql works fine:
`gcc mysqlTesttemperature.c -o mysqlTesttemperature $(mysql_config --cflags --libs)`

It seems to be a conflict between t_list.h and my_list.h.

Idea how to fix this?

**Comment by smlng** [comment]
Please test your COAP functionality (without mysql) first. The above problem seams to be related to incompatible types of mysql and coap. Thus, its a separate/new issue, lets close this one first ...

**Comment by MonsterCode8000** [comment]
so now I tested the client and it looks fine:
pi@raspberrypi ~/libcoap/examples $ ./client -m get coap://[fe80::5bb3:4e48:6fdc:6002%lowpan0]/temperature
2816281628172822

The response of the previous installed client is very similar:
pi@raspberrypi ~/libcoap/examples $ coap-client -m get coap://[fe80::5bb3:4e48:6fdc:6002%lowpan0]/temperature
v:1 t:CON c:GET i:7430 {} [ ]
28312830282628262823

The first line is different but the main thing is to get temperatures   and so on.

**Comment by smlng** [comment]
So COAP works, and we can close this issue?

**Comment by MonsterCode8000** [comment]
I agree

**Comment by patel-priyanka** [comment]
hi all,
i am using obgm/libcoap/coap-server code to fetch temperature sensor value using raspberry but i am unable to understand how and which code has to insert for temperature sensor resource.plz help...
