### ISSUE TITLE
delete files

### ISSUE THREAD

**Issue by smlng** [smartuni/Environ.me#3]
Delete empty or temporary files, such as
- [Unbekanntes Dokument.txt](https://github.com/smartuni/Environ.me/blob/master/Webserver/Unbenanntes%20Dokument.txt)
- [index.html~](https://github.com/smartuni/Environ.me/blob/master/Webserver/development/index.html%7E)

**Comment by PeterKietzmann** [comment]
It seems there are duplicate folders (of older project versions) e.g. LEDundSensoren and sensor_node. Please delete superfluous folders or **at least** sort and mark outdated versions.

**Comment by PeterKietzmann** [comment]
Please remove commented code like e.g.[here](https://github.com/smartuni/Environ.me/blob/master/sensor_node/sensors.c#L26)

**Comment by PeterKietzmann** [comment]
Please remove commented code like [here](https://github.com/smartuni/Environ.me/blob/master/sensor_node/sensors.c#L26)

**Comment by MonsterCode8000** [comment]
Deleted files

```
Unbekanntes Dokument.txt
index.html~
test.html~
```

**Comment by smlng** [comment]
end of project
