### ISSUE TITLE
libcoap and Mysql

### ISSUE THREAD

**Issue by MonsterCode8000** [smartuni/Environ.me#6]
I added the mysql stuff into the example client.
Then the compiler failed:

```
$ gcc -Wall -Wextra -I /usr/local/include/coap -L/usr/local/lib client.c coap_list.c -o client $(mysql_config --cflags --libs) -lcoap-1 -DWITH_POSIX`
[...]
In file included from /usr/local/include/coap/coap.h:50:0,
                 from client.c:28:
/usr/local/include/coap/t_list.h:105:1: error: conflicting types for ‘list_add’
/usr/include/mysql/my_list.h:30:14: note: previous declaration of ‘list_add’ was here
/usr/local/include/coap/t_list.h:111:1: error: expected ‘)’ before ‘the_list’
/usr/local/include/coap/t_list.h:116:1: error: expected identifier or ‘(’ before ‘{’ token
/usr/local/include/coap/t_list.h:116:27: error: expected identifier or ‘(’ before ‘{’ token
/usr/local/include/coap/t_list.h: In function ‘list_insert’:
/usr/local/include/coap/t_list.h:128:5: warning: passing argument 2 of ‘list_cons’ from incompatible pointer type [enabled by default]
/usr/include/mysql/my_list.h:32:14: note: expected ‘struct LIST *’ but argument is of type ‘list_t’
/usr/local/include/coap/t_list.h:128:5: warning: assignment from incompatible pointer type [enabled by default]'
```

A test program with only Mysql works fine:
`gcc mysqlTesttemperature.c -o mysqlTesttemperature $(mysql_config --cflags --libs)`

It seems to be a conflict between t_list.h and my_list.h.

Idea how to fix this?

**Comment by smlng** [comment]
Try to replace/rename all occurrences of `list_t` in `<libcoap>/include/coap/t_list.h`, e.g. with `mylist_t` and recompile/install libcoap. The problem is that libcoap and mysql define a list struct with the same name.

**Comment by MonsterCode8000** [comment]
I did the renaming.
It helped a bit but there is still the strange error see below.

gcc -Wall -Wextra -I /usr/local/include/coap -L/usr/local/lib client.c coap_list.c -o client `mysql_config --cflags --libs` -lcoap-1 -DWITH_POSIX
warnings...
coap_config.h:115:0: note: this is the location of the previous definition
In file included from /usr/local/include/coap/coap.h:50:0,
                 from client.c:29:
/usr/local/include/coap/t_list.h:111:1: error: expected ‘)’ before ‘the_list’
/usr/local/include/coap/t_list.h:116:1: error: expected identifier or ‘(’ before ‘{’ token
/usr/local/include/coap/t_list.h:116:29: error: expected identifier or ‘(’ before ‘{’ token
/usr/local/include/coap/t_list.h: In function ‘list_insert’:
/usr/local/include/coap/t_list.h:128:5: warning: passing argument 2 of ‘list_cons’ from incompatible pointer type [enabled by default]
/usr/include/mysql/my_list.h:32:14: note: expected ‘struct LIST *’ but argument is of type ‘mylist_t’
/usr/local/include/coap/t_list.h:128:5: warning: assignment from incompatible pointer type [enabled by default]

I looked into the file t_list.h but I could not find any arrow mistake.
The modified t_list.h is attached as TXT.

[t_list.txt](https://github.com/smartuni/Environ.me/files/82942/t_list.txt)

**Comment by smlng** [comment]
Arrg, it looks like mysql is already defining some `mylist_t` too, so you must re-rename your `mylist_t` to something else, but _not_ `coap_list_t` because that is already taken by libcoap. So think of something else ... 

In your modified t_list.txt I saw that you renamed `list_add` to `mylist_add` (L 105), this probably wrong?!

**Comment by MonsterCode8000** [comment]
it is still there plus the error: conflicting types for ‘list_add’.
I feel like walking from one trapdoor to the next trapdoor. It is very annoying.

Terminal output:

In file included from /usr/local/include/coap/coap.h:50:0,
                 from client.c:29:
/usr/local/include/coap/t_list.h:105:1: error: conflicting types for ‘list_add’
/usr/include/mysql/my_list.h:30:14: note: previous declaration of ‘list_add’ was here
/usr/local/include/coap/t_list.h:111:1: error: expected ‘)’ before ‘the_list’
/usr/local/include/coap/t_list.h:116:1: error: expected identifier or ‘(’ before ‘{’ token
/usr/local/include/coap/t_list.h:116:36: error: expected identifier or ‘(’ before ‘{’ token
/usr/local/include/coap/t_list.h: In function ‘list_insert’:
/usr/local/include/coap/t_list.h:128:5: warning: passing argument 2 of ‘list_cons’ from incompatible pointer type [enabled by default]
/usr/include/mysql/my_list.h:32:14: note: expected ‘struct LIST *’ but argument is of type ‘myLibcoapList_t’
/usr/local/include/coap/t_list.h:128:5: warning: assignment from incompatible pointer type [enabled by default]

[t_list.txt](https://github.com/smartuni/Environ.me/files/83064/t_list.txt)

**Comment by smlng** [comment]
You may be right. Anyway, I took another look into the code and haven't found any part using this `list_t` stuff anyway. So I commented the include in `libcoap/include/coap/coap.h.in` line 50 like this `//#include "t_list.h"`. Then re-run `make`  and `make install`.

**Comment by MonsterCode8000** [comment]
cool it works "a close trapdoor"!
Now I can work with Mysql and I can close this issue.
Thanks a lot!
